// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env for local dev; skip gracefully in Docker where env vars are injected
try { require("dotenv/config"); } catch {}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "postgresql://postgres:postgres@localhost:5432/postgres",
  },
});
