import { NextRequest, NextResponse } from "next/server";
import { getAgentSession, getUserById } from "@/lib/db";
import JSZip from "jszip";

const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET;
const PDF_SERVICE_URL = process.env.PDF_SERVICE_URL || "https://pdf.perricheno.ru/api/v1";
const PDF_API_KEY = process.env.PDF_API_KEY || "0a69f4b4-0210-47c0-a2a9-946e3e894c4c";

/**
 * Determine if a session is a "visual" (bot-generated Python/R code)
 * or a "research" (LaTeX document generated by the agent).
 */
function isVisualSession(session: any): boolean {
    return session.doc_type === 'visual';
}

/**
 * Get the visualization source code from a session.
 * For visual sessions: stream_text holds the Python/R code.
 * For research sessions: stream_text holds partial generation artifacts, main_tex holds the LaTeX.
 */
function getVisualCode(session: any): string | null {
    if (isVisualSession(session)) {
        return session.stream_text || null;
    }
    return null;
}

/**
 * Detect language from code content.
 */
function detectLanguage(code: string): 'python' | 'r' {
    // Python indicators
    if (code.includes("import ") || code.includes("plt.") || code.includes("sns.") || code.includes("pandas") || code.includes("def ")) {
        return 'python';
    }
    // R indicators
    if (code.includes("library(") || code.includes("ggplot") || code.includes("<-") || code.includes("geom_")) {
        return 'r';
    }
    return 'python'; // default
}

export async function POST(req: NextRequest) {
    const secret = req.headers.get("x-bot-secret");
    if (secret !== WEBHOOK_SECRET) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    try {
        const { sessionId, type } = await req.json();
        const session = getAgentSession(sessionId);

        if (!session) {
            return NextResponse.json({ error: "Session not found" }, { status: 404 });
        }

        // =====================
        // ZIP — always works
        // =====================
        if (type === "zip") {
            const zip = new JSZip();
            
            // For research sessions: include LaTeX source
            if (session.main_tex) {
                zip.file("main.tex", session.main_tex);
            }
            
            // For visual sessions: include the generated code
            const visualCode = getVisualCode(session);
            if (visualCode) {
                const lang = detectLanguage(visualCode);
                zip.file(`visual.${lang === 'python' ? 'py' : 'R'}`, visualCode);
            }
            
            if (session.references_bib) {
                zip.file("references.bib", session.references_bib);
            }

            // Include compiled visuals if any (images + source code)
            if (session.visuals_json) {
                try {
                    const visuals = JSON.parse(session.visuals_json);
                    const imgFolder = zip.folder("images");
                    visuals.forEach((v: any, i: number) => {
                        if (v.image) {
                            const base64Data = v.image.replace(/^data:image\/\w+;base64,/, "");
                            imgFolder?.file(`fig_${i + 1}_${v.chart_type || "chart"}.png`, base64Data, { base64: true });
                        }
                        if (v.source_code && !visualCode) {
                            // Only add if we didn't already add stream_text
                            const ext = v.language === 'r' ? 'R' : 'py';
                            zip.file(`code_${i + 1}.${ext}`, v.source_code);
                        }
                    });
                } catch (e) { /* visuals_json might be invalid */ }
            }

            const content = await zip.generateAsync({ type: "nodebuffer" });
            return new NextResponse(content as any, {
                headers: {
                    "Content-Type": "application/zip",
                    "Content-Disposition": `attachment; filename="project_${sessionId.slice(0, 8)}.zip"`,
                },
            });
        }

        // =====================
        // PDF
        // =====================
        if (type === "pdf") {
            const content = session.main_tex || session.stream_text;
            
            if (!content) {
                return NextResponse.json({ error: "Нет содержимого для генерации PDF." }, { status: 404 });
            }

            // For research sessions with LaTeX: use the dedicated LaTeX compiler microservice
            // (same approach as /api/agent/compile-pdf)
            if (session.main_tex && !isVisualSession(session)) {
                const COMPILER_URL = process.env.LATEX_COMPILER_URL;
                const COMPILER_KEY = process.env.LATEX_COMPILER_KEY;

                if (COMPILER_URL && COMPILER_KEY) {
                    try {
                        // Build a ZIP with main.tex + references.bib (same as the agent compile flow)
                        const zip = new JSZip();
                        zip.file("main.tex", session.main_tex);
                        if (session.references_bib) {
                            zip.file("references.bib", session.references_bib);
                        }
                        const zipBuffer = await zip.generateAsync({ type: "arraybuffer" });

                        const proxyFormData = new FormData();
                        proxyFormData.append("file", new Blob([zipBuffer]), "project.zip");

                        const compilerRes = await fetch(COMPILER_URL, {
                            method: "POST",
                            headers: { "x-api-key": COMPILER_KEY },
                            body: proxyFormData,
                            signal: AbortSignal.timeout(90000),
                        });

                        if (compilerRes.ok) {
                            const ct = compilerRes.headers.get("content-type") || "";
                            if (!ct.includes("json") && !ct.includes("text")) {
                                // Got a real PDF back
                                const pdfBuffer = await compilerRes.arrayBuffer();
                                return new NextResponse(pdfBuffer as any, {
                                    headers: {
                                        "Content-Type": "application/pdf",
                                        "Content-Disposition": `attachment; filename="report_${sessionId.slice(0, 8)}.pdf"`,
                                    },
                                });
                            }
                        }
                        console.warn("LaTeX compiler failed, falling back to markdown-to-pdf");
                    } catch (err) {
                        console.error("LaTeX compiler error:", err);
                    }
                }
            }
            
            // Fallback: markdown-to-pdf (for visual sessions or when LaTeX compiler is unavailable)
            try {
                const mdFormData = new FormData();
                const mdBlob = new Blob([content], { type: "text/markdown" });
                mdFormData.append("fileInput", mdBlob, "document.md");

                const mdRes = await fetch(`${PDF_SERVICE_URL}/convert/markdown/pdf`, {
                    method: "POST",
                    headers: { "X-API-KEY": PDF_API_KEY },
                    body: mdFormData
                });

                if (mdRes.ok) {
                    const pdfBuffer = await mdRes.arrayBuffer();
                    return new NextResponse(pdfBuffer as any, {
                        headers: {
                            "Content-Type": "application/pdf",
                            "Content-Disposition": `attachment; filename="report_${sessionId.slice(0, 8)}.pdf"`,
                        },
                    });
                }
            } catch (err) {
                console.error("PDF markdown fallback error:", err);
            }
            return NextResponse.json({ error: "Не удалось скомпилировать PDF. Используйте ZIP." }, { status: 500 });
        }

        // =====================
        // IMAGES (charts)
        // =====================
        if (type === "images") {
            if (!session.visuals_json) {
                return NextResponse.json({ visuals: [] });
            }
            try {
                const visuals = JSON.parse(session.visuals_json);
                return NextResponse.json({ visuals: visuals.map((v: any) => ({ image: v.image, chart_type: v.chart_type })) });
            } catch (e) {
                return NextResponse.json({ visuals: [] });
            }
        }

        // =====================
        // CODE (source code download)
        // =====================
        if (type === "code") {
            // For visual sessions: return the generated Python/R code from stream_text
            const visualCode = getVisualCode(session);
            if (visualCode && visualCode.length > 10) {
                const lang = detectLanguage(visualCode);
                const ext = lang === 'python' ? 'py' : 'R';
                return new NextResponse(visualCode, {
                    headers: {
                        "Content-Type": "text/plain; charset=utf-8",
                        "Content-Disposition": `attachment; filename="visual_${sessionId.slice(0, 8)}.${ext}"`,
                    },
                });
            }

            // For research sessions: return the LaTeX source
            if (session.main_tex) {
                return new NextResponse(session.main_tex, {
                    headers: {
                        "Content-Type": "text/plain; charset=utf-8",
                        "Content-Disposition": `attachment; filename="main_${sessionId.slice(0, 8)}.tex"`,
                    },
                });
            }
            
            // Fallback: check visuals_json for source_code
            if (session.visuals_json) {
                try {
                    const visuals = JSON.parse(session.visuals_json);
                    if (visuals.length === 1 && visuals[0].source_code) {
                        const v = visuals[0];
                        const lang = detectLanguage(v.source_code);
                        const ext = lang === 'python' ? 'py' : 'R';
                        return new NextResponse(v.source_code, {
                            headers: {
                                "Content-Type": "text/plain; charset=utf-8",
                                "Content-Disposition": `attachment; filename="visual_${sessionId.slice(0, 8)}.${ext}"`,
                            },
                        });
                    } else if (visuals.length > 1) {
                        const zip = new JSZip();
                        visuals.forEach((v: any, i: number) => {
                            if (v.source_code) {
                                const lang = detectLanguage(v.source_code);
                                zip.file(`visual_${i + 1}.${lang === 'python' ? 'py' : 'R'}`, v.source_code);
                            }
                        });
                        const content = await zip.generateAsync({ type: "nodebuffer" });
                        return new NextResponse(content as any, {
                            headers: {
                                "Content-Type": "application/zip",
                                "Content-Disposition": `attachment; filename="source_codes_${sessionId.slice(0, 8)}.zip"`,
                            },
                        });
                    }
                } catch (e) { /* ignore parse errors */ }
            }
            
            return NextResponse.json({ error: "Код для этой сессии отсутствует." }, { status: 404 });
        }

        return NextResponse.json({ error: "Invalid type" }, { status: 400 });
    } catch (err: any) {
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
