-- PostgreSQL Migration Schema for Perricheno

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id TEXT UNIQUE NOT NULL,
    username TEXT,
    first_name TEXT,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    plan_tier TEXT DEFAULT 'free',
    account_tier TEXT DEFAULT 'free',
    daily_chars_used BIGINT DEFAULT 0,
    weekly_chars_used BIGINT DEFAULT 0,
    monthly_chars_used BIGINT DEFAULT 0,
    purchased_chars BIGINT DEFAULT 0,
    daily_visuals_used BIGINT DEFAULT 0,
    purchased_visuals BIGINT DEFAULT 0,
    daily_reports_used BIGINT DEFAULT 0,
    purchased_reports BIGINT DEFAULT 0,
    
    last_reset_date TEXT,
    last_week_reset TEXT,
    is_banned BOOLEAN DEFAULT false,
    is_admin BOOLEAN DEFAULT false,
    is_deleted BOOLEAN DEFAULT false,
    referred_by BIGINT
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    task_text TEXT NOT NULL,
    remind_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE chat_sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE agent_sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    doc_type TEXT DEFAULT 'research',
    settings_json TEXT,
    main_tex TEXT,
    references_bib TEXT,
    visuals_json TEXT,
    share_id TEXT UNIQUE,
    status TEXT DEFAULT 'done',
    error_msg TEXT,
    stream_text TEXT,
    tg_message_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE chat_messages (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    metadata_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE visual_assets (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT REFERENCES chat_sessions(id) ON DELETE SET NULL,
    type TEXT NOT NULL,
    url TEXT NOT NULL,
    source_code TEXT,
    prompt TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE bot_sessions (
    telegram_id TEXT PRIMARY KEY,
    session_data TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_agent TEXT,
    ip TEXT,
    location TEXT,
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE auth_requests (
    token TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'pending',
    tg_user_data TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic TEXT NOT NULL,
    amount_text TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE receipts (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    pack_name TEXT NOT NULL,
    amount_text TEXT NOT NULL,
    pdf_base64 TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE processed_payments (
    order_id TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    tokens BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL,
    amount BIGINT NOT NULL,
    uses BIGINT DEFAULT 0,
    max_uses BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE promo_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(promo_id, user_id)
);

CREATE TABLE system_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE system_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE latex_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    error_text TEXT NOT NULL,
    session_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RPC For Deducting Usage Safely

CREATE OR REPLACE FUNCTION deduct_user_usage(
    p_user_id BIGINT,
    p_free_deduction BIGINT,
    p_purchased_deduction BIGINT,
    p_amount BIGINT
) RETURNS void AS $$
BEGIN
    -- Update user balance: track ALL usage in daily/weekly/monthly, deduct purchased separately
    UPDATE users 
    SET 
        daily_chars_used = daily_chars_used + p_amount,
        weekly_chars_used = weekly_chars_used + p_amount,
        monthly_chars_used = COALESCE(monthly_chars_used, 0) + p_amount,
        purchased_chars = purchased_chars - p_purchased_deduction
    WHERE id = p_user_id;

    -- Record transaction if amount > 0
    IF p_amount > 0 THEN
        INSERT INTO transactions (user_id, topic, amount_text, is_positive)
        VALUES (p_user_id, 'Agent generation', '-' || p_amount || ' chars', false);

        INSERT INTO usage_logs (user_id, tokens)
        VALUES (p_user_id, p_amount);
    END IF;
END;
$$ LANGUAGE plpgsql;

