"use client";

import Link from "next/link";
import { IconArrowLeft } from "@tabler/icons-react";
import { motion } from "framer-motion";

export default function PrivacyPage() {
    return (
        <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)] p-6 md:p-12 lg:p-20 font-sans selection:bg-black selection:text-white">
            <Link href="/" className="inline-flex items-center gap-2 text-sm opacity-40 hover:opacity-100 transition-opacity mb-12 group">
                <IconArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> Back to Home
            </Link>

            <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="max-w-4xl mx-auto"
            >
                <div className="mb-20">
                    <h1 className="text-4xl md:text-6xl font-bold tracking-tighter mb-4">Privacy Policy.</h1>
                    <p className="text-xl opacity-40">Privacy & Data Protection for Perricheno Inc. platforms.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-16 md:gap-24">
                    {/* ENGLISH VERSION */}
                    <div className="space-y-8 text-[15px] leading-relaxed opacity-80">
                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">1. Information Collection</h2>
                            <p>Perricheno collects minimum data necessary for platform functionality. This includes your Telegram ID (for login), chat logs (to provide context to LLMs), and session persistence data (document drafts, R-visualizations).</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">2. AI Data Processing</h2>
                            <p>Information you provide in prompts and documents generated by the platform may be processed by third-party AI models (e.g., OpenAI/Anthropic/Google). We encourage users not to provide highly sensitive personal or corporate data.</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">3. Data Retention</h2>
                            <p>Your session data is stored in our database for as long as you maintain an account or until you delete the specific session. You may delete all your session data at any time via the sidebar controls.</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">4. Security</h2>
                            <p>We use standard database encryption and secure API communication (HTTPS) to protect your data. However, no internet-based service can be guaranteed 100% secure.</p>
                        </section>
                    </div>

                    {/* RUSSIAN VERSION */}
                    <div className="space-y-8 text-[15px] leading-relaxed opacity-80 border-t border-[var(--border)] pt-8 md:border-t-0 md:pt-0">
                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">1. Сбор информации</h2>
                            <p>Perricheno собирает минимальный объем данных, необходимый для работы платформы. Сюда входят: ваш Telegram ID (для входа), логи чата и данные сессий (черновики документов LaTeX, визуализации).</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">2. Обработка данных ИИ</h2>
                            <p>Ваши запросы (промпты) и сгенерированные документы могут обрабатываться сторонними моделями ИИ (OpenAI/Anthropic). Мы настоятельно рекомендуем не предоставлять конфиденциальные личные данные.</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">3. Хранение данных</h2>
                            <p>Данные ваших сессий хранятся в нашей базе до тех пор, пока вы не удалите их вручную через боковое меню или не закроете сессию. Все данные могут быть удалены пользователем безвозвратно.</p>
                        </section>

                        <section>
                            <h2 className="text-black font-bold uppercase tracking-widest text-[11px] mb-4">4. Безопасность</h2>
                            <p>Мы используем шифрование баз данных и защищенные протоколы связи (HTTPS) для защиты ваших данных. Однако ни один интернет-сервис не может быть защищен на 100%.</p>
                        </section>
                    </div>
                </div>

                <footer className="mt-24 pt-8 border-t border-[var(--border)] opacity-30 text-[11px] uppercase tracking-widest">
                    Last Updated: March 30, 2026 • © Perricheno Inc.
                </footer>
            </motion.div>
        </div>
    );
}
